### PR TITLE
Add projectlombok version

### PR DESCRIPTION
**Pull request by Jimbasler-pivotal**
This fixes an issue with the mvn install command that would error out without it.

### CODE REVIEW

**Comment by Jimbasler-pivotal** [comment]
At least a few people have run into an issue with the projectlombok dependency.  Adding version fixes it.

**Comment by mborges-pivotal** [comment]
were you able to merge this? I'm seeing a different version in the pom.xml, so I'm not sure where we are with this. Let me know and I'll merge the pull request. Thanks!

**Comment by Jimbasler-pivotal** [comment]
It looks like it is there now.

Thanks.

Jim



*Jim Basler* | Pivotal
Cloud Application and Platform Architect
Agile Strategy, Transformation, and Enterprise Architecture (TOGAF)
Ph: 1-920-410-6408 | *jbasler@pivotal.io <jbasler@pivotal.io>*

*Platform as a Service | Agile Development | Big Data*
www.Pivotal.io <http://www.pivotal.io/>

*Our mission is to transform how the world builds software.*
In 2013 Pivotal was deliberately created to be a *special company*. A
company built on an indelible culture, based on a common set of values and
beliefs called the *Pivotal Principles*—*Do What Works, Do What**’**s
Right, Be Kind*. Great companies are built by great cultures.

[image: SpringOne 2016] <http://springoneplatform.io/>

**Comment by Jimbasler-pivotal** [comment]
I saw someone else had a pull request, so I closed mine with a comment.  Note that I used Lombok 1.16.8 which is a little more recent and it worked fine.

**Comment by mborges-pivotal** [comment]
Ah, now it makes sense. Should we re-open yours and get the most recent version? Let me know whatever is easier for you. I'm in favor to reopening and adding the most recent version. Thanks!

**Comment by Jimbasler-pivotal** [comment]
Reopening to add more recent version.

**Comment by Jimbasler-pivotal** [comment]
Done.  I reopened it.

Thanks.

Jim



*Jim Basler* | Pivotal
Cloud Application and Platform Architect
Agile Strategy, Transformation, and Enterprise Architecture (TOGAF)
Ph: 1-920-410-6408 | *jbasler@pivotal.io <jbasler@pivotal.io>*

*Platform as a Service | Agile Development | Big Data*
www.Pivotal.io <http://www.pivotal.io/>

*Our mission is to transform how the world builds software.*
In 2013 Pivotal was deliberately created to be a *special company*. A
company built on an indelible culture, based on a common set of values and
beliefs called the *Pivotal Principles*—*Do What Works, Do What**’**s
Right, Be Kind*. Great companies are built by great cultures.

[image: SpringOne 2016] <http://springoneplatform.io/>

**Pull request merged**
